/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/drivers/src/altera_avalon_uart_init.c File Reference
#include <fcntl.h>
*
#include `sys/alt_dev.h`
*
#include `sys/alt_irq.h`
*
#include `sys/ioctl.h`
*
#include `sys/alt_errno.h`
*
#include `altera_avalon_uart.h`
*
#include `altera_avalon_uart_regs.h`
*
Functions
static void altera_avalon_uart_irq (void *context, alt_u32 id)
static void altera_avalon_uart_rxirq (altera_avalon_uart_state *sp, alt_u32 status)
static void altera_avalon_uart_txirq (altera_avalon_uart_state *sp, alt_u32 status)
void altera_avalon_uart_init (altera_avalon_uart_state *sp, alt_u32 irq_controller_id, alt_u32 irq)
int altera_avalon_uart_close (altera_avalon_uart_state *sp, int flags)
Function Documentation
int altera_avalon_uart_close (altera_avalon_uart_state * sp, int flags)
Definition at line 298 of file altera_avalon_uart_init.c.
References altera_avalon_uart_state_s::tx_end, and altera_avalon_uart_state_s::tx_start.
Referenced by altera_avalon_uart_close_fd().
void altera_avalon_uart_init (altera_avalon_uart_state * sp, alt_u32 irq_controller_id, alt_u32 irq)
Definition at line 66 of file altera_avalon_uart_init.c.
References ALT_FLAG_CREATE, alt_irq_register(), ALT_SEM_CREATE, ALTERA_AVALON_UART_CONTROL_DCTS_MSK, ALTERA_AVALON_UART_CONTROL_RRDY_MSK, ALTERA_AVALON_UART_CONTROL_RTS_MSK, altera_avalon_uart_irq(), altera_avalon_uart_state_s::base, altera_avalon_uart_state_s::ctrl, and IOWR_ALTERA_AVALON_UART_CONTROL.
static void altera_avalon_uart_irq (void * context, alt_u32 id) [static]
Definition at line 109 of file altera_avalon_uart_init.c.
References altera_avalon_uart_rxirq(), ALTERA_AVALON_UART_STATUS_DCTS_MSK, ALTERA_AVALON_UART_STATUS_RRDY_MSK, ALTERA_AVALON_UART_STATUS_TRDY_MSK, altera_avalon_uart_txirq(), altera_avalon_uart_state_s::base, IORD_ALTERA_AVALON_UART_STATUS, and IOWR_ALTERA_AVALON_UART_STATUS.
Referenced by altera_avalon_uart_init().
static void altera_avalon_uart_rxirq (altera_avalon_uart_state * sp, alt_u32 status) [static]
Definition at line 153 of file altera_avalon_uart_init.c.
References ALT_AVALON_UART_BUF_MSK, ALT_FLAG_POST, ALT_UART_READ_RDY, ALTERA_AVALON_UART_CONTROL_RRDY_MSK, ALTERA_AVALON_UART_STATUS_FE_MSK, ALTERA_AVALON_UART_STATUS_PE_MSK, altera_avalon_uart_state_s::base, altera_avalon_uart_state_s::ctrl, IORD_ALTERA_AVALON_UART_RXDATA, IOWR_ALTERA_AVALON_UART_CONTROL, altera_avalon_uart_state_s::rx_end, and altera_avalon_uart_state_s::rx_start.
Referenced by altera_avalon_uart_irq().
static void altera_avalon_uart_txirq (altera_avalon_uart_state * sp, alt_u32 status) [static]
Definition at line 207 of file altera_avalon_uart_init.c.
References ALT_AVALON_UART_BUF_MSK, ALT_AVALON_UART_FC, ALT_FLAG_POST, ALT_UART_WRITE_RDY, ALTERA_AVALON_UART_CONTROL_DCTS_MSK, ALTERA_AVALON_UART_CONTROL_TRDY_MSK, ALTERA_AVALON_UART_STATUS_CTS_MSK, altera_avalon_uart_state_s::base, altera_avalon_uart_state_s::ctrl, altera_avalon_uart_state_s::flags, IORD_ALTERA_AVALON_UART_STATUS, IOWR_ALTERA_AVALON_UART_CONTROL, IOWR_ALTERA_AVALON_UART_TXDATA, altera_avalon_uart_state_s::tx_buf, altera_avalon_uart_state_s::tx_end, and altera_avalon_uart_state_s::tx_start.
Referenced by altera_avalon_uart_irq().