/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/inc/sys/alt_dma.h File Reference
#include `sys/alt_dma_dev.h`
*
#include `alt_types.h`
*
#include <errno.h>
*
Functions
alt_dma_txchan alt_dma_txchan_open (const char *name)
static ALT_INLINE int alt_dma_txchan_close (alt_dma_txchan dma)
static ALT_INLINE int alt_dma_txchan_send (alt_dma_txchan dma, const void *from, alt_u32 length, alt_txchan_done *done, void *handle)
static ALT_INLINE int alt_dma_txchan_space (alt_dma_txchan dma)
static ALT_INLINE int alt_dma_txchan_ioctl (alt_dma_txchan dma, int req, void *arg)
alt_dma_rxchan alt_dma_rxchan_open (const char *dev)
static ALT_INLINE int alt_dma_rxchan_close (alt_dma_rxchan dma)
static ALT_INLINE int alt_dma_rxchan_prepare (alt_dma_rxchan dma, void *data, alt_u32 len, alt_rxchan_done *done, void *handle)
static ALT_INLINE int alt_dma_rxchan_ioctl (alt_dma_rxchan dma, int req, void *arg)
static ALT_INLINE alt_u32 alt_dma_rxchan_depth (alt_dma_rxchan dma)
Function Documentation
static ALT_INLINE int alt_dma_rxchan_close (alt_dma_rxchan dma) [static]
Definition at line 157 of file alt_dma.h.
static ALT_INLINE alt_u32 alt_dma_rxchan_depth (alt_dma_rxchan dma) [static]
Definition at line 213 of file alt_dma.h.
References alt_dma_rxchan_dev_s::depth.
static ALT_INLINE int alt_dma_rxchan_ioctl (alt_dma_rxchan dma, int req, void * arg) [static]
Definition at line 201 of file alt_dma.h.
References alt_dma_rxchan_dev_s::ioctl.
alt_dma_rxchan alt_dma_rxchan_open (const char * dev)
Definition at line 51 of file alt_dma_rxchan_open.c.
References ALT_ERRNO, and alt_find_dev().
Referenced by alt_dma_txchan_ioctl().
static ALT_INLINE int alt_dma_rxchan_prepare (alt_dma_rxchan dma, void * data, alt_u32 len, alt_rxchan_done * done, void * handle) [static]
Definition at line 182 of file alt_dma.h.
References alt_dma_rxchan_dev_s::prepare.
static ALT_INLINE int alt_dma_txchan_close (alt_dma_txchan dma) [static]
Definition at line 80 of file alt_dma.h.
static ALT_INLINE int alt_dma_txchan_ioctl (alt_dma_txchan dma, int req, void * arg) [static]
Definition at line 134 of file alt_dma.h.
References alt_dma_rxchan_open(), and alt_dma_txchan_dev_s::ioctl.
alt_dma_txchan alt_dma_txchan_open (const char * name)
Definition at line 51 of file alt_dma_txchan_open.c.
References ALT_ERRNO, and alt_find_dev().
static ALT_INLINE int alt_dma_txchan_send (alt_dma_txchan dma, const void * from, alt_u32 length, alt_txchan_done * done, void * handle) [static]
Definition at line 99 of file alt_dma.h.
References alt_dma_txchan_dev_s::dma_send.
static ALT_INLINE int alt_dma_txchan_space (alt_dma_txchan dma) [static]
Definition at line 119 of file alt_dma.h.
References alt_dma_txchan_dev_s::space.