/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_main.c File Reference
#include <stdio.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <fcntl.h>
*
#include <stdlib.h>
*
#include <unistd.h>
*
#include `sys/alt_dev.h`
*
#include `sys/alt_sys_init.h`
*
#include `sys/alt_irq.h`
*
#include `os/alt_hooks.h`
*
#include `priv/alt_file.h`
*
#include `alt_types.h`
*
#include `system.h`
*
#include `sys/alt_log_printf.h`
*
Functions
void _do_ctors (void)
void _do_dtors (void)
int main (int, char **, char **)
void alt_main (void)
Variables
int alt_argc = 0
char ** alt_argv = {NULL}
char ** alt_envp = {NULL}
Function Documentation
void _do_ctors (void)
Definition at line 58 of file alt_do_ctors.c.
References __CTOR_END__, and __CTOR_LIST__.
Referenced by alt_main().
void _do_dtors (void)
Definition at line 58 of file alt_do_dtors.c.
References __DTOR_END__, and __DTOR_LIST__.
Referenced by alt_main().
void alt_main (void)
Definition at line 82 of file alt_main.c.
References _do_ctors(), _do_dtors(), alt_argc, alt_argv, alt_envp, alt_io_redirect(), alt_irq_init(), ALT_LOG_PRINT_BOOT, ALT_OS_INIT, ALT_SEM_CREATE, ALT_STDERR, ALT_STDIN, ALT_STDOUT, alt_sys_init(), and main().
int main (int , char ** , char **)
Referenced by alt_main().
Variable Documentation
int alt_argc = 0
Definition at line 64 of file alt_main.c.
Referenced by alt_main(), and alt_set_args().
char** alt_argv = {NULL}
Definition at line 65 of file alt_main.c.
Referenced by alt_main(), and alt_set_args().
char** alt_envp = {NULL}
Definition at line 66 of file alt_main.c.
Referenced by alt_main(), and alt_set_args().