/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/inc/sys/alt_irq.h File Reference
#include <errno.h>
*
#include `nios2.h`
*
#include `alt_types.h`
*
#include `system.h`
*
#include `priv/alt_legacy_irq.h`
*
Macros
#define ALT_IRQ_ENABLED 1
#define ALT_IRQ_DISABLED 0
#define ALT_NIRQ NIOS2_NIRQ
Typedefs
typedef int alt_irq_context
typedef void(* alt_isr_func) (void *isr_context, alt_u32 id)
Functions
static ALT_INLINE int ALT_ALWAYS_INLINE alt_irq_enabled (void)
static ALT_INLINE alt_irq_context ALT_ALWAYS_INLINE alt_irq_disable_all (void)
static ALT_INLINE void ALT_ALWAYS_INLINE alt_irq_enable_all (alt_irq_context context)
void alt_irq_init (const void *base)
static ALT_INLINE void ALT_ALWAYS_INLINE alt_irq_cpu_enable_interrupts (void)
static ALT_INLINE alt_u32 ALT_ALWAYS_INLINE alt_irq_pending (void)
Macro Definition Documentation
#define ALT_IRQ_DISABLED 0
Definition at line 63 of file alt_irq.h.
#define ALT_IRQ_ENABLED 1
Definition at line 62 of file alt_irq.h.
#define ALT_NIRQ NIOS2_NIRQ
Definition at line 68 of file alt_irq.h.
Referenced by alt_irq_register().
Typedef Documentation
typedef int alt_irq_context
Definition at line 73 of file alt_irq.h.
typedef void(* alt_isr_func) (void *isr_context, alt_u32 id)
Definition at line 79 of file alt_irq.h.
Function Documentation
static ALT_INLINE void ALT_ALWAYS_INLINE alt_irq_cpu_enable_interrupts (void) [static]
Definition at line 176 of file alt_irq.h.
References NIOS2_STATUS_PIE_MSK, NIOS2_STATUS_RSIE_MSK, and NIOS2_WRITE_STATUS.
Referenced by alt_irq_init().
static ALT_INLINE alt_irq_context ALT_ALWAYS_INLINE alt_irq_disable_all (void) [static]
Definition at line 114 of file alt_irq.h.
References ALT_ALWAYS_INLINE, ALT_INLINE, NIOS2_READ_STATUS, NIOS2_STATUS_PIE_MSK, and NIOS2_WRITE_STATUS.
Referenced by __mcount_record(), alt_alarm_start(), alt_alarm_stop(), alt_irq_disable(), alt_irq_enable(), alt_irq_register(), ALT_SBRK(), altera_avalon_uart_read(), and altera_avalon_uart_write().
static ALT_INLINE void ALT_ALWAYS_INLINE alt_irq_enable_all (alt_irq_context context) [static]
Definition at line 144 of file alt_irq.h.
References ALT_ALWAYS_INLINE, ALT_INLINE, alt_irq_init(), NIOS2_READ_STATUS, NIOS2_STATUS_PIE_MSK, and NIOS2_WRITE_STATUS.
Referenced by __mcount_record(), alt_alarm_start(), alt_alarm_stop(), alt_irq_disable(), alt_irq_enable(), alt_irq_register(), ALT_SBRK(), altera_avalon_uart_read(), and altera_avalon_uart_write().
static ALT_INLINE int ALT_ALWAYS_INLINE alt_irq_enabled (void) [static]
Definition at line 96 of file alt_irq.h.
References ALT_ALWAYS_INLINE, ALT_INLINE, NIOS2_READ_STATUS, and NIOS2_STATUS_PIE_MSK.
void alt_irq_init (const void * base)
Definition at line 85 of file alt_sys_init.c.
References alt_irq_cpu_enable_interrupts(), and ALTERA_NIOS2_GEN2_IRQ_INIT.
Referenced by alt_irq_enable_all(), and alt_main().
static ALT_INLINE alt_u32 ALT_ALWAYS_INLINE alt_irq_pending (void) [static]
Definition at line 231 of file alt_irq.h.
References NIOS2_READ_IPENDING.
Referenced by alt_irq_handler().