/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/inc/sys/alt_alarm.h File Reference
#include `alt_llist.h`
*
#include `alt_types.h`
*
#include `priv/alt_alarm.h`
*
Typedefs
typedef struct alt_alarm_s alt_alarm
Functions
int alt_alarm_start (alt_alarm *the_alarm, alt_u32 nticks, alt_u32(*callback)(void *context), void *context)
void alt_alarm_stop (alt_alarm *the_alarm)
static ALT_INLINE alt_u32 ALT_ALWAYS_INLINE alt_ticks_per_second (void)
static ALT_INLINE int ALT_ALWAYS_INLINE alt_sysclk_init (alt_u32 nticks)
static ALT_INLINE alt_u32 ALT_ALWAYS_INLINE alt_nticks (void)
void alt_tick (void)
Typedef Documentation
typedef struct alt_alarm_s alt_alarm
Definition at line 59 of file alt_alarm.h.
Function Documentation
int alt_alarm_start (alt_alarm * the_alarm, alt_u32 nticks, alt_u32(*)(void *context) callback, void * context)
Definition at line 64 of file alt_alarm_start.c.
References alt_alarm_list, alt_irq_disable_all(), alt_irq_enable_all(), alt_llist_insert(), alt_nticks(), alt_ticks_per_second(), alt_alarm_s::callback, alt_alarm_s::context, alt_alarm_s::llist, alt_alarm_s::rollover, and alt_alarm_s::time.
Referenced by __mcount_record().
void alt_alarm_stop (alt_alarm * the_alarm)
Definition at line 66 of file alt_tick.c.
References alt_irq_disable_all(), alt_irq_enable_all(), alt_llist_remove(), and alt_alarm_s::llist.
Referenced by alt_tick().
static ALT_INLINE alt_u32 ALT_ALWAYS_INLINE alt_nticks (void) [static]
Definition at line 110 of file alt_alarm.h.
References _alt_nticks, and alt_tick().
Referenced by alt_alarm_start(), ALT_GETTIMEOFDAY(), ALT_SETTIMEOFDAY(), and ALT_TIMES().
static ALT_INLINE int ALT_ALWAYS_INLINE alt_sysclk_init (alt_u32 nticks) [static]
Definition at line 93 of file alt_alarm.h.
References _alt_tick_rate.
void alt_tick (void)
Definition at line 87 of file alt_tick.c.
References _alt_nticks, alt_alarm_list, alt_alarm_stop(), ALT_OS_TIME_TICK, alt_alarm_s::callback, alt_alarm_s::context, if(), alt_alarm_s::llist, alt_llist_s::next, alt_alarm_s::rollover, and alt_alarm_s::time.
Referenced by alt_nticks().
static ALT_INLINE alt_u32 ALT_ALWAYS_INLINE alt_ticks_per_second (void) [static]
Definition at line 83 of file alt_alarm.h.
References _alt_tick_rate.
Referenced by __mcount_record(), alt_alarm_start(), ALT_GETTIMEOFDAY(), ALT_SETTIMEOFDAY(), and ALT_TIMES().