/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_app/spi_flash_lib.c File Reference
#include `spi_flash_lib.h`
*
#include <altera_avalon_spi.h>
*
#include `sodera_pcie_brd_v1r0.h`
*
Functions
uint8_t ReverseBitOrder (uint8_t data)
Reverses bit order.
void FlashSpiFastRead (CyBool_t v)
uint8_t FlashSpiTransfer (alt_u32 SPIBase, alt_u32 SPISlave, uint32_t pageAddress, uint16_t byteCount, uint8_t *buffer, CyBool_t isRead)
uint8_t CyFxSpiWaitForStatus (alt_u32 SPIBase, alt_u32 SPISlave)
uint8_t FlashSpiEraseSector (alt_u32 SPIBase, alt_u32 SPISlave, uint8_t isErase, uint8_t sector)
Variables
char spiFastRead = 0
Function Documentation
uint8_t CyFxSpiWaitForStatus (alt_u32 SPIBase, alt_u32 SPISlave)
Definition at line 134 of file spi_flash_lib.c.
References alt_avalon_spi_command(), FLASH_CMD_PAGE_READST, FLASH_CMD_PAGE_WRITEEN, and STATUS_RETRIES.
Referenced by FlashSpiTransfer().
uint8_t FlashSpiEraseSector (alt_u32 SPIBase, alt_u32 SPISlave, uint8_t isErase, uint8_t sector)
Definition at line 184 of file spi_flash_lib.c.
References alt_avalon_spi_command(), FLASH_CMD_PAGE_READST, FLASH_CMD_PAGE_WRITEEN, FLASH_CMD_SECTOR_ERASE, FLASH_SECTOR_SIZE, ReverseBitOrder(), and STATUS_RETRIES_ERASE.
void FlashSpiFastRead (CyBool_t v)
Definition at line 26 of file spi_flash_lib.c.
References spiFastRead.
uint8_t FlashSpiTransfer (alt_u32 SPIBase, alt_u32 SPISlave, uint32_t pageAddress, uint16_t byteCount, uint8_t * buffer, CyBool_t isRead)
Definition at line 31 of file spi_flash_lib.c.
References alt_avalon_spi_command(), ALT_AVALON_SPI_COMMAND_MERGE, CyFxSpiWaitForStatus(), FLASH_CMD_PAGE_READ, FLASH_CMD_PAGE_WRITE, FLASH_PAGE_SIZE, ReverseBitOrder(), and spiFastRead.
uint8_t ReverseBitOrder (uint8_t data)
Reverses bit order.
Definition at line 16 of file spi_flash_lib.c.
References data.
Referenced by FlashSpiEraseSector(), and FlashSpiTransfer().
Variable Documentation
char spiFastRead = 0
Definition at line 25 of file spi_flash_lib.c.
Referenced by FlashSpiFastRead(), and FlashSpiTransfer().