/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/inc/priv/alt_dev_llist.h File Reference
#include `sys/alt_llist.h`
*
#include `alt_types.h`
*
Classes
struct alt_dev_llist
Functions
int alt_dev_llist_insert (alt_dev_llist *dev, alt_llist *list)
Function Documentation
int alt_dev_llist_insert (alt_dev_llist * dev, alt_llist * list)
Definition at line 40 of file alt_dev_llist_insert.c.
References ALT_ERRNO, alt_llist_insert(), alt_dev_llist::llist, and alt_dev_llist::name.
Referenced by alt_dev_reg(), alt_dma_rxchan_reg(), alt_dma_txchan_reg(), and alt_flash_device_register().