/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/inc/priv/alt_legacy_irq.h File Reference
#include <errno.h>
*
#include `system.h`
*
#include `nios2.h`
*
#include `alt_types.h`
*
#include `sys/alt_irq.h`
*
Functions
int alt_irq_register (alt_u32 id, void *context, alt_isr_func handler)
static ALT_INLINE int ALT_ALWAYS_INLINE alt_irq_disable (alt_u32 id)
static ALT_INLINE int ALT_ALWAYS_INLINE alt_irq_enable (alt_u32 id)
static ALT_INLINE alt_u32 ALT_ALWAYS_INLINE alt_irq_interruptible (alt_u32 priority)
static ALT_INLINE void ALT_ALWAYS_INLINE alt_irq_non_interruptible (alt_u32 mask)
Function Documentation
static ALT_INLINE int ALT_ALWAYS_INLINE alt_irq_disable (alt_u32 id) [static]
Definition at line 68 of file alt_legacy_irq.h.
References alt_irq_active, alt_irq_disable_all(), alt_irq_enable_all(), and NIOS2_WRITE_IENABLE.
Referenced by alt_irq_register().
static ALT_INLINE int ALT_ALWAYS_INLINE alt_irq_enable (alt_u32 id) [static]
Definition at line 86 of file alt_legacy_irq.h.
References alt_irq_active, alt_irq_disable_all(), alt_irq_enable_all(), and NIOS2_WRITE_IENABLE.
Referenced by alt_irq_register().
static ALT_INLINE alt_u32 ALT_ALWAYS_INLINE alt_irq_interruptible (alt_u32 priority) [static]
Definition at line 118 of file alt_legacy_irq.h.
References alt_irq_active, alt_priority_mask, NIOS2_WRITE_IENABLE, and NIOS2_WRITE_STATUS.
static ALT_INLINE void ALT_ALWAYS_INLINE alt_irq_non_interruptible (alt_u32 mask) [static]
Definition at line 139 of file alt_legacy_irq.h.
References alt_irq_active, alt_priority_mask, NIOS2_WRITE_IENABLE, and NIOS2_WRITE_STATUS.
int alt_irq_register (alt_u32 id, void * context, alt_isr_func handler)
Definition at line 75 of file alt_irq_register.c.
References alt_irq, alt_irq_disable(), alt_irq_disable_all(), alt_irq_enable(), alt_irq_enable_all(), ALT_NIRQ, ALT_IRQ_HANDLER::context, and ALT_IRQ_HANDLER::handler.
Referenced by altera_avalon_uart_init().