/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/drivers/src/altera_avalon_uart_fd.c File Reference
#include `alt_types.h`
*
#include `sys/alt_dev.h`
*
#include `altera_avalon_uart.h`
*
Functions
int altera_avalon_uart_read (altera_avalon_uart_state *sp, char *buffer, int space, int flags)
int altera_avalon_uart_write (altera_avalon_uart_state *sp, const char *ptr, int count, int flags)
int altera_avalon_uart_ioctl (altera_avalon_uart_state *sp, int req, void *arg)
int altera_avalon_uart_close (altera_avalon_uart_state *sp, int flags)
int altera_avalon_uart_read_fd (alt_fd *fd, char *buffer, int space)
int altera_avalon_uart_write_fd (alt_fd *fd, const char *buffer, int space)
int altera_avalon_uart_close_fd (alt_fd *fd)
Function Documentation
int altera_avalon_uart_close (altera_avalon_uart_state * sp, int flags)
Definition at line 298 of file altera_avalon_uart_init.c.
References altera_avalon_uart_state_s::tx_end, and altera_avalon_uart_state_s::tx_start.
Referenced by altera_avalon_uart_close_fd().
int altera_avalon_uart_close_fd (alt_fd * fd)
Definition at line 93 of file altera_avalon_uart_fd.c.
References altera_avalon_uart_close(), alt_fd_s::dev, alt_fd_s::fd_flags, and altera_avalon_uart_dev_s::state.
int altera_avalon_uart_ioctl (altera_avalon_uart_state * sp, int req, void * arg)
Referenced by altera_avalon_uart_write_fd().
int altera_avalon_uart_read (altera_avalon_uart_state * sp, char * buffer, int space, int flags)
Definition at line 124 of file altera_avalon_uart_read.c.
References ALT_AVALON_UART_BUF_MSK, ALT_ERRNO, ALT_FLAG_PEND, alt_irq_disable_all(), alt_irq_enable_all(), ALT_SEM_PEND, ALT_SEM_POST, ALT_UART_READ_RDY, ALTERA_AVALON_UART_CONTROL_RRDY_MSK, altera_avalon_uart_state_s::base, block, altera_avalon_uart_state_s::ctrl, IOWR_ALTERA_AVALON_UART_CONTROL, altera_avalon_uart_state_s::rx_end, and altera_avalon_uart_state_s::rx_start.
Referenced by altera_avalon_uart_read_fd().
int altera_avalon_uart_read_fd (alt_fd * fd, char * buffer, int space)
Definition at line 50 of file altera_avalon_uart_fd.c.
References altera_avalon_uart_read(), alt_fd_s::dev, alt_fd_s::fd_flags, and altera_avalon_uart_dev_s::state.
int altera_avalon_uart_write (altera_avalon_uart_state * sp, const char * ptr, int count, int flags)
Definition at line 124 of file altera_avalon_uart_write.c.
References ALT_AVALON_UART_BUF_MSK, ALT_ERRNO, ALT_FLAG_PEND, alt_irq_disable_all(), alt_irq_enable_all(), ALT_SEM_PEND, ALT_SEM_POST, ALT_UART_WRITE_RDY, ALTERA_AVALON_UART_CONTROL_DCTS_MSK, ALTERA_AVALON_UART_CONTROL_TRDY_MSK, altera_avalon_uart_state_s::base, altera_avalon_uart_state_s::ctrl, IOWR_ALTERA_AVALON_UART_CONTROL, altera_avalon_uart_state_s::tx_buf, altera_avalon_uart_state_s::tx_end, and altera_avalon_uart_state_s::tx_start.
Referenced by altera_avalon_uart_write_fd().
int altera_avalon_uart_write_fd (alt_fd * fd, const char * buffer, int space)
Definition at line 59 of file altera_avalon_uart_fd.c.
References altera_avalon_uart_ioctl(), altera_avalon_uart_ioctl_fd(), altera_avalon_uart_write(), alt_fd_s::dev, alt_fd_s::fd_flags, and altera_avalon_uart_dev_s::state.