/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/alt_sys_init.c File Reference
#include `system.h`
*
#include `sys/alt_irq.h`
*
#include `sys/alt_sys_init.h`
*
#include <stddef.h>
*
#include `altera_nios2_gen2_irq.h`
*
#include `altera_avalon_spi.h`
*
#include `altera_avalon_sysid_qsys.h`
*
#include `i2c_opencores.h`
*
Functions
ALTERA_NIOS2_GEN2_IRQ_INSTANCE (NIOS2_CPU, nios2_cpu)
ALTERA_AVALON_SPI_INSTANCE (SPI_1_ADF, spi_1_ADF)
ALTERA_AVALON_SPI_INSTANCE (SPI_1_DAC, spi_1_DAC)
ALTERA_AVALON_SPI_INSTANCE (SPI_LMS, spi_lms)
ALTERA_AVALON_SYSID_QSYS_INSTANCE (SYSID_QSYS_0, sysid_qsys_0)
I2C_OPENCORES_INSTANCE (I2C_OPENCORES_0, i2c_opencores_0)
void alt_irq_init (const void *base)
void alt_sys_init (void)
Function Documentation
void alt_irq_init (const void * base)
Definition at line 85 of file alt_sys_init.c.
References alt_irq_cpu_enable_interrupts(), and ALTERA_NIOS2_GEN2_IRQ_INIT.
Referenced by alt_irq_enable_all(), and alt_main().
void alt_sys_init (void)
Definition at line 96 of file alt_sys_init.c.
References ALTERA_AVALON_SPI_INIT, ALTERA_AVALON_SYSID_QSYS_INIT, and I2C_OPENCORES_INIT.
Referenced by alt_main().
ALTERA_AVALON_SPI_INSTANCE (SPI_1_ADF , spi_1_ADF)
ALTERA_AVALON_SPI_INSTANCE (SPI_1_DAC , spi_1_DAC)
ALTERA_AVALON_SPI_INSTANCE (SPI_LMS , spi_lms)
ALTERA_AVALON_SYSID_QSYS_INSTANCE (SYSID_QSYS_0 , sysid_qsys_0)
ALTERA_NIOS2_GEN2_IRQ_INSTANCE (NIOS2_CPU , nios2_cpu)
I2C_OPENCORES_INSTANCE (I2C_OPENCORES_0 , i2c_opencores_0)