/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_sbrk.c File Reference
#include <sys/types.h>
*
#include `os/alt_syscall.h`
*
#include `sys/alt_irq.h`
*
#include `sys/alt_stack.h`
*
#include `system.h`
*
Functions
caddr_t ALT_SBRK (int incr) __attribute__((no_instrument_function))
Variables
char __alt_heap_start []
char __alt_heap_limit []
static char * heap_end = __alt_heap_start
Function Documentation
caddr_t ALT_SBRK (int incr)
Definition at line 68 of file alt_sbrk.c.
References __alt_heap_limit, __alt_heap_start, alt_irq_disable_all(), alt_irq_enable_all(), alt_report_stack_overflow(), alt_set_stack_limit(), alt_stack_limit(), alt_stack_pointer(), and heap_end.
Variable Documentation
char __alt_heap_limit[]
Referenced by ALT_SBRK().
char __alt_heap_start[]
Referenced by ALT_SBRK().
char* heap_end = __alt_heap_start [static]
Definition at line 60 of file alt_sbrk.c.
Referenced by ALT_SBRK().