/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_release_fd.c File Reference
#include `sys/alt_dev.h`
*
#include `priv/alt_file.h`
*
Functions
void alt_release_fd (int fd)
Function Documentation
void alt_release_fd (int fd)
Definition at line 44 of file alt_release_fd.c.
References alt_fd_list, alt_fd_s::dev, and alt_fd_s::fd_flags.
Referenced by ALT_CLOSE(), ALT_OPEN(), and alt_open_fd().