/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_io_redirect.c File Reference
#include <stddef.h>
*
#include <stdio.h>
*
#include <unistd.h>
*
#include <fcntl.h>
*
#include `sys/alt_dev.h`
*
#include `priv/alt_file.h`
*
Functions
static void alt_open_fd (alt_fd *fd, const char *name, int flags, int mode)
void alt_io_redirect (const char *stdout_dev, const char *stdin_dev, const char *stderr_dev)
Function Documentation
void alt_io_redirect (const char * stdout_dev, const char * stdin_dev, const char * stderr_dev)
Definition at line 85 of file alt_io_redirect.c.
References alt_fd_list, and alt_open_fd().
Referenced by alt_main().
static void alt_open_fd (alt_fd * fd, const char * name, int flags, int mode) [static]
Definition at line 58 of file alt_io_redirect.c.
References alt_fd_list, alt_release_fd(), alt_fd_s::dev, alt_fd_s::fd_flags, and alt_fd_s::priv.
Referenced by alt_io_redirect().