/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_alarm_start.c File Reference
#include <errno.h>
*
#include `sys/alt_alarm.h`
*
#include `sys/alt_irq.h`
*
Functions
int alt_alarm_start (alt_alarm *alarm, alt_u32 nticks, alt_u32(*callback)(void *context), void *context)
Function Documentation
int alt_alarm_start (alt_alarm * alarm, alt_u32 nticks, alt_u32(*)(void *context) callback, void * context)
Definition at line 64 of file alt_alarm_start.c.
References alt_alarm_list, alt_irq_disable_all(), alt_irq_enable_all(), alt_llist_insert(), alt_nticks(), alt_ticks_per_second(), alt_alarm_s::callback, alt_alarm_s::context, alt_alarm_s::llist, alt_alarm_s::rollover, and alt_alarm_s::time.
Referenced by __mcount_record().