/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_open.c File Reference
#include `sys/alt_errno.h`
*
#include `sys/alt_warning.h`
*
#include `priv/alt_file.h`
*
#include `alt_types.h`
*
#include `os/alt_syscall.h`
*
Functions
static int alt_file_locked (alt_fd *fd)
int ALT_OPEN (const char *file, int flags, int mode)
Variables
alt_llist alt_dev_list
Function Documentation
static int alt_file_locked (alt_fd * fd) [static]
Definition at line 64 of file alt_open.c.
References ALT_FD_DEV, ALT_FD_EXCL, alt_fd_list, alt_max_fd, alt_fd_s::dev, and alt_fd_s::fd_flags.
Referenced by ALT_OPEN().
int ALT_OPEN (const char * file, int flags, int mode)
Definition at line 105 of file alt_open.c.
References ALT_ERRNO, ALT_FD_FLAGS_MASK, alt_fd_list, alt_file_locked(), alt_find_dev(), alt_find_file(), alt_get_fd(), alt_release_fd(), alt_fd_s::fd_flags, and alt_dev_s::open.
Variable Documentation
alt_llist alt_dev_list
Definition at line 68 of file alt_dev.c.