/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_tick.c File Reference
#include `sys/alt_irq.h`
*
#include `sys/alt_alarm.h`
*
#include `os/alt_hooks.h`
*
#include `alt_types.h`
*
Functions
ALT_LLIST_HEAD (alt_alarm_list)
void alt_alarm_stop (alt_alarm *alarm)
void alt_tick (void)
Variables
alt_u32 _alt_tick_rate = 0
volatile alt_u32 _alt_nticks = 0
Function Documentation
void alt_alarm_stop (alt_alarm * alarm)
Definition at line 66 of file alt_tick.c.
References alt_irq_disable_all(), alt_irq_enable_all(), alt_llist_remove(), and alt_alarm_s::llist.
Referenced by alt_tick().
ALT_LLIST_HEAD (alt_alarm_list)
void alt_tick (void)
Definition at line 87 of file alt_tick.c.
References _alt_nticks, alt_alarm_list, alt_alarm_stop(), ALT_OS_TIME_TICK, alt_alarm_s::callback, alt_alarm_s::context, if(), alt_alarm_s::llist, alt_llist_s::next, alt_alarm_s::rollover, and alt_alarm_s::time.
Referenced by alt_nticks().
Variable Documentation
volatile alt_u32 _alt_nticks = 0
Definition at line 51 of file alt_tick.c.
Referenced by alt_nticks(), and alt_tick().
alt_u32 _alt_tick_rate = 0
Definition at line 44 of file alt_tick.c.
Referenced by alt_sysclk_init(), and alt_ticks_per_second().