/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/inc/sys/alt_llist.h File Reference
#include `alt_types.h`
*
Classes
struct alt_llist_s
Macros
#define ALT_LLIST_HEAD(head) alt_llist head = {&head, &head}
#define ALT_LLIST_ENTRY {0, 0}
Typedefs
typedef struct alt_llist_s alt_llist
Functions
static ALT_INLINE void ALT_ALWAYS_INLINE alt_llist_insert (alt_llist *list, alt_llist *entry)
static ALT_INLINE void ALT_ALWAYS_INLINE alt_llist_remove (alt_llist *entry)
Macro Definition Documentation
#define ALT_LLIST_ENTRY {0, 0}
Definition at line 83 of file alt_llist.h.
#define ALT_LLIST_HEAD(head) alt_llist head = {&head, &head}
Definition at line 75 of file alt_llist.h.
Typedef Documentation
typedef struct alt_llist_s alt_llist
Definition at line 62 of file alt_llist.h.
Function Documentation
static ALT_INLINE void ALT_ALWAYS_INLINE alt_llist_insert (alt_llist * list, alt_llist * entry) [static]
Definition at line 90 of file alt_llist.h.
References alt_llist_s::next, and alt_llist_s::previous.
Referenced by alt_alarm_start(), alt_dev_llist_insert(), and alt_fs_reg().
static ALT_INLINE void ALT_ALWAYS_INLINE alt_llist_remove (alt_llist * entry) [static]
Definition at line 105 of file alt_llist.h.
References alt_llist_s::next, and alt_llist_s::previous.
Referenced by alt_alarm_stop().