/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/drivers/src/altera_avalon_uart_write.c File Reference
#include <fcntl.h>
*
#include `sys/alt_dev.h`
*
#include `sys/alt_irq.h`
*
#include `sys/ioctl.h`
*
#include `sys/alt_errno.h`
*
#include `altera_avalon_uart_regs.h`
*
#include `altera_avalon_uart.h`
*
Functions
int altera_avalon_uart_write (altera_avalon_uart_state *sp, const char *ptr, int len, int flags)
Function Documentation
int altera_avalon_uart_write (altera_avalon_uart_state * sp, const char * ptr, int len, int flags)
Definition at line 124 of file altera_avalon_uart_write.c.
References ALT_AVALON_UART_BUF_MSK, ALT_ERRNO, ALT_FLAG_PEND, alt_irq_disable_all(), alt_irq_enable_all(), ALT_SEM_PEND, ALT_SEM_POST, ALT_UART_WRITE_RDY, ALTERA_AVALON_UART_CONTROL_DCTS_MSK, ALTERA_AVALON_UART_CONTROL_TRDY_MSK, altera_avalon_uart_state_s::base, altera_avalon_uart_state_s::ctrl, IOWR_ALTERA_AVALON_UART_CONTROL, altera_avalon_uart_state_s::tx_buf, altera_avalon_uart_state_s::tx_end, and altera_avalon_uart_state_s::tx_start.
Referenced by altera_avalon_uart_write_fd().