/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/inc/sys/alt_stack.h File Reference
#include `nios2.h`
*
#include `alt_types.h`
*
Functions
static ALT_INLINE char *ALT_ALWAYS_INLINE alt_stack_limit (void)
static ALT_INLINE char *ALT_ALWAYS_INLINE alt_stack_pointer (void)
static ALT_INLINE void ALT_ALWAYS_INLINE alt_set_stack_limit (char *limit)
static ALT_INLINE void ALT_ALWAYS_INLINE alt_report_stack_overflow (void)
Variables
char * alt_stack_limit_value
Function Documentation
static ALT_INLINE void ALT_ALWAYS_INLINE alt_report_stack_overflow (void) [static]
Definition at line 115 of file alt_stack.h.
References NIOS2_REPORT_STACK_OVERFLOW.
Referenced by ALT_SBRK().
static ALT_INLINE void ALT_ALWAYS_INLINE alt_set_stack_limit (char * limit) [static]
Definition at line 105 of file alt_stack.h.
References NIOS2_WRITE_ET.
Referenced by ALT_SBRK().
static ALT_INLINE char* ALT_ALWAYS_INLINE alt_stack_limit (void) [static]
Definition at line 61 of file alt_stack.h.
References NIOS2_READ_ET.
Referenced by ALT_SBRK().
static ALT_INLINE char* ALT_ALWAYS_INLINE alt_stack_pointer (void) [static]
Definition at line 74 of file alt_stack.h.
References ALT_ALWAYS_INLINE, ALT_INLINE, and NIOS2_READ_SP.
Referenced by ALT_SBRK().
Variable Documentation
char* alt_stack_limit_value