/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_gmon.c File Reference
#include <assert.h>
*
#include <string.h>
*
#include <unistd.h>
*
#include `priv/nios2_gmon_data.h`
*
#include `sys/alt_irq.h`
*
#include `sys/alt_alarm.h`
*
Classes
struct mcount_fn_arc
struct mcount_fn_entry
Macros
#define PCSAMPLE_BYTES_PER_BUCKET 32
#define NIOS2_READ_EA(dest) __asm__ (`mov %0, ea` : `=r` (dest))
#define HASH_BUCKETS 64 /* Must be a power of 2 */
#define MCOUNT_SLAB_INCREMENT 1020
Functions
void __mcount_record (void *self_pc, void *from_pc, struct mcount_fn_entry *fn_entry, struct mcount_fn_entry **fn_head) __attribute__((no_instrument_function))
static __inline__ void * mcount_allocate (unsigned int size) __attribute__((no_instrument_function))
static int nios2_pcsample_init (void)
static alt_u32 nios2_pcsample (void *context)
Variables
static char * mcount_slab_ptr = 0
static int mcount_slab_size = 0
Macro Definition Documentation
#define HASH_BUCKETS 64 /* Must be a power of 2 */
Referenced by nios2_pcsample_init().
#define MCOUNT_SLAB_INCREMENT 1020
Definition at line 123 of file alt_gmon.c.
Referenced by mcount_allocate().
#define NIOS2_READ_EA(dest) __asm__ (`mov %0, ea` : `=r` (dest))
Definition at line 46 of file alt_gmon.c.
Referenced by nios2_pcsample().
#define PCSAMPLE_BYTES_PER_BUCKET 32
Definition at line 44 of file alt_gmon.c.
Referenced by __mcount_record(), nios2_pcsample(), and nios2_pcsample_init().
Function Documentation
void __mcount_record (void * self_pc, void * from_pc, struct mcount_fn_entry * fn_entry, struct mcount_fn_entry ** fn_head)
Definition at line 159 of file alt_gmon.c.
References alt_alarm_start(), alt_irq_disable_all(), alt_irq_enable_all(), alt_ticks_per_second(), mcount_fn_entry::arc_head, mcount_fn_arc::count, mcount_fn_arc::from_pc, GMON_DATA_PROFILE_DATA, GMON_DATA_PROFILE_RATE, mcount_allocate(), mcount_fn_arc::next, mcount_fn_entry::next, nios2_pcsample(), nios2_pcsample_init(), PCSAMPLE_BYTES_PER_BUCKET, and mcount_fn_entry::self_pc.
static __inline__ void * mcount_allocate (unsigned int size) [static]
Definition at line 133 of file alt_gmon.c.
References data, MCOUNT_SLAB_INCREMENT, and mcount_slab_ptr.
Referenced by __mcount_record().
static alt_u32 nios2_pcsample (void * context) [static]
Definition at line 248 of file alt_gmon.c.
References NIOS2_READ_EA, and PCSAMPLE_BYTES_PER_BUCKET.
Referenced by __mcount_record().
static int nios2_pcsample_init (void) [static]
Definition at line 79 of file alt_gmon.c.
References GMON_DATA_SIZE, HASH_BUCKETS, and PCSAMPLE_BYTES_PER_BUCKET.
Referenced by __mcount_record().
Variable Documentation
char* mcount_slab_ptr = 0 [static]
Definition at line 120 of file alt_gmon.c.
Referenced by mcount_allocate().
int mcount_slab_size = 0 [static]
Definition at line 121 of file alt_gmon.c.