/home/erik/git/dev/LimeSDR-USB_GW/ip/i2c_opencores_v13/Docs/I2C_tests.c File Reference
#include <stdio.h>
*
#include `system.h`
*
#include `i2c_opencores.h`
*
Functions
int main ()
Function Documentation
int main ()
Definition at line 19 of file I2C_tests.c.
References ALT_CPU_FREQ, data, I2C_init(), I2C_read(), I2C_start(), and I2C_write().