/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_irq_register.c File Reference
#include <errno.h>
*
#include `system.h`
*
#include `sys/alt_irq.h`
*
#include `priv/alt_legacy_irq.h`
*
#include `os/alt_hooks.h`
*
#include `alt_types.h`
*
#include `sys/alt_irq_entry.h`
*
#include `priv/alt_irq_table.h`
*
Functions
int alt_irq_register (alt_u32 id, void *context, alt_isr_func handler)
Function Documentation
int alt_irq_register (alt_u32 id, void * context, alt_isr_func handler)
Definition at line 75 of file alt_irq_register.c.
References alt_irq, alt_irq_disable(), alt_irq_disable_all(), alt_irq_enable(), alt_irq_enable_all(), ALT_NIRQ, ALT_IRQ_HANDLER::context, and ALT_IRQ_HANDLER::handler.
Referenced by altera_avalon_uart_init().