/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/drivers/inc/altera_avalon_uart_fd.h File Reference
#include `sys/alt_dev.h`
*
Classes
struct altera_avalon_uart_dev_s
Macros
#define ALTERA_AVALON_UART_IOCTL_FD NULL
#define ALTERA_AVALON_UART_DEV_INSTANCE(name, d)
#define ALTERA_AVALON_UART_DEV_INIT(name, d)
Typedefs
typedef struct altera_avalon_uart_dev_s altera_avalon_uart_dev
Functions
int altera_avalon_uart_read_fd (alt_fd *fd, char *ptr, int len)
int altera_avalon_uart_write_fd (alt_fd *fd, const char *ptr, int len)
int altera_avalon_uart_ioctl_fd (alt_fd *fd, int req, void *arg)
int altera_avalon_uart_close_fd (alt_fd *fd)
Macro Definition Documentation
#define ALTERA_AVALON_UART_DEV_INIT(name, d)
Value:
{
    ALTERA_AVALON_UART_STATE_INIT(name, d.state); \
                                                       \
    /* make the device available to the system */
    alt_dev_reg(&d.dev); \
  }
Definition at line 129 of file altera_avalon_uart_fd.h.
#define ALTERA_AVALON_UART_DEV_INSTANCE(name, d)
Definition at line 96 of file altera_avalon_uart_fd.h.
#define ALTERA_AVALON_UART_IOCTL_FD NULL
Definition at line 93 of file altera_avalon_uart_fd.h.
Typedef Documentation
typedef struct altera_avalon_uart_dev_s altera_avalon_uart_dev
Function Documentation
int altera_avalon_uart_close_fd (alt_fd * fd)
Definition at line 93 of file altera_avalon_uart_fd.c.
References altera_avalon_uart_close(), alt_fd_s::dev, alt_fd_s::fd_flags, and altera_avalon_uart_dev_s::state.
int altera_avalon_uart_ioctl_fd (alt_fd * fd, int req, void * arg)
Referenced by altera_avalon_uart_write_fd().
int altera_avalon_uart_read_fd (alt_fd * fd, char * ptr, int len)
Definition at line 50 of file altera_avalon_uart_fd.c.
References altera_avalon_uart_read(), alt_fd_s::dev, alt_fd_s::fd_flags, and altera_avalon_uart_dev_s::state.
int altera_avalon_uart_write_fd (alt_fd * fd, const char * ptr, int len)
Definition at line 59 of file altera_avalon_uart_fd.c.
References altera_avalon_uart_ioctl(), altera_avalon_uart_ioctl_fd(), altera_avalon_uart_write(), alt_fd_s::dev, alt_fd_s::fd_flags, and altera_avalon_uart_dev_s::state.