/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_app/main.c File Reference
#include `io.h`
*
#include `system.h`
*
#include <stdint.h>
*
#include <string.h>
*
#include <altera_avalon_spi.h>
*
#include `alt_types.h`
*
#include `LMS64C_protocol.h`
*
#include `sodera_pcie_brd_v1r0.h`
*
#include `i2c_opencores.h`
*
Macros
#define sbi(p, n) ((p) |= (1UL << (n)))
#define cbi(p, n) ((p) &= ~(1 << (n)))
#define FW_VER 4
#define SPI_NR_LMS7002M 0
#define SPI_NR_BRD 1
#define SPI_NR_DAC 0
#define SPI_NR_ADF4002 0
#define PROG_EEPROM 1
#define PROG_SRAM 2
#define BOOT_MCU 3
#define MCU_CONTROL_REG 0x02
CMD_PROG_MCU.
#define MCU_STATUS_REG 0x03
#define MCU_FIFO_WR_REG 0x04
#define MAX_MCU_RETRIES 30
Functions
unsigned char Check_many_blocks (unsigned char block_size)
This function checks if all blocks could fit in data field.
void getFifoData (uint8_t *buf, uint8_t k)
Gets 64 bytes packet from FIFO.
void set_led (unsigned char led_pattern)
Gets led_pattern as parameter in order to write to the register.
void Configure_LM75 (void)
Configures LM75.
void Control_TCXO_DAC (unsigned char oe, unsigned char *data)
Function to control DAC for TCXO frequency control.
void Control_TCXO_ADF (unsigned char oe, unsigned char *data)
Function to control ADF for TCXO frequency control.
int main ()
Main, what else? Gets LEDs pattern from switchers.
Variables
uint8_t MCU_retries
uint8_t test
uint8_t block
uint8_t cmd_errors
uint8_t glEp0Buffer_Rx [64]
uint8_t glEp0Buffer_Tx [64]
tLMS_Ctrl_Packet * LMS_Ctrl_Packet_Tx = (tLMS_Ctrl_Packet*)glEp0Buffer_Tx
tLMS_Ctrl_Packet * LMS_Ctrl_Packet_Rx = (tLMS_Ctrl_Packet*)glEp0Buffer_Rx
unsigned char dac_val = 134
unsigned char dac_data [2]
signed short int converted_val = 300
int flash_page = 0
int flash_page_data_cnt = 0
int flash_data_cnt_free = 0
int flash_data_counter_to_copy = 0
unsigned long int last_portion
unsigned long int current_portion
unsigned long int fpga_data
unsigned char data_cnt
unsigned char sc_brdg_data [4]
unsigned char flash_page_data [0x100]
tBoard_Config_FPGA * Board_Config_FPGA = (tBoard_Config_FPGA*) flash_page_data
unsigned long int fpga_byte
Macro Definition Documentation
#define BOOT_MCU 3
Definition at line 40 of file main.c.
Referenced by main().
#define cbi(p, n) ((p) &= ~(1 << (n)))
Definition at line 23 of file main.c.
Referenced by main().
#define FW_VER 4
Definition at line 28 of file main.c.
Referenced by main().
#define MAX_MCU_RETRIES 30
Definition at line 47 of file main.c.
Referenced by main().
#define MCU_CONTROL_REG 0x02
CMD_PROG_MCU.
Definition at line 43 of file main.c.
Referenced by main().
#define MCU_FIFO_WR_REG 0x04
Definition at line 45 of file main.c.
Referenced by main().
#define MCU_STATUS_REG 0x03
Definition at line 44 of file main.c.
Referenced by main().
#define PROG_EEPROM 1
Definition at line 38 of file main.c.
Referenced by main().
#define PROG_SRAM 2
Definition at line 39 of file main.c.
Referenced by main().
#define sbi(p, n) ((p) |= (1UL << (n)))
Definition at line 22 of file main.c.
Referenced by main().
#define SPI_NR_ADF4002 0
Definition at line 34 of file main.c.
Referenced by Control_TCXO_ADF().
#define SPI_NR_BRD 1
Definition at line 32 of file main.c.
Referenced by main().
#define SPI_NR_DAC 0
Definition at line 33 of file main.c.
Referenced by Control_TCXO_DAC().
#define SPI_NR_LMS7002M 0
Definition at line 31 of file main.c.
Referenced by main().
Function Documentation
unsigned char Check_many_blocks (unsigned char block_size)
This function checks if all blocks could fit in data field.
If blocks will not fit, function returns TRUE.
Definition at line 72 of file main.c.
References tLMS_Ctrl_Header::Data_blocks, tLMS_Ctrl_Packet::Data_field, tLMS_Ctrl_Packet::Header, tLMS_Ctrl_Header::Status, and STATUS_BLOCKS_ERROR_CMD.
Referenced by main().
void Configure_LM75 (void)
Configures LM75.
Definition at line 110 of file main.c.
References I2C_OPENCORES_0_BASE, I2C_start(), I2C_write(), and LM75_I2C_ADDR.
Referenced by main().
void Control_TCXO_ADF (unsigned char oe, unsigned char * data)
Function to control ADF for TCXO frequency control.
Parameters
oe output enable control: 0 - output disabled, 1 - output enabled
data pointer to ADF data block (3 bytes)
Definition at line 194 of file main.c.
References alt_avalon_spi_command(), SPI_1_ADF_BASE, and SPI_NR_ADF4002.
Referenced by main().
void Control_TCXO_DAC (unsigned char oe, unsigned char * data)
Function to control DAC for TCXO frequency control.
Parameters
oe output enable control: 0 - output disabled, 1 - output enabled
data pointer to DAC value (1 byte)
Definition at line 168 of file main.c.
References alt_avalon_spi_command(), SPI_1_DAC_BASE, and SPI_NR_DAC.
Referenced by main().
void getFifoData (uint8_t * buf, uint8_t k)
Gets 64 bytes packet from FIFO.
Definition at line 86 of file main.c.
References AV_FIFO_INT_0_BASE, and IORD.
Referenced by main().
int main ()
Main, what else? Gets LEDs pattern from switchers.
Sets LEDs register according to the pattern.
Definition at line 236 of file main.c.
References alt_avalon_spi_command(), ALT_CPU_FREQ, AV_FIFO_INT_0_BASE, block, BOOT_MCU, cbi, Check_many_blocks(), CMD_ADF4002_WR, CMD_ANALOG_VAL_RD, CMD_ANALOG_VAL_WR, CMD_BRDSPI16_RD, CMD_BRDSPI16_WR, cmd_errors, CMD_GET_INFO, CMD_GPIO_DIR_RD, CMD_GPIO_DIR_WR, CMD_GPIO_RD, CMD_GPIO_WR, CMD_LMS7002_RD, CMD_LMS7002_WR, CMD_LMS_MCU_FW_WR, CMD_LMS_RST, tLMS_Ctrl_Header::Command, Configure_LM75(), Control_TCXO_ADF(), Control_TCXO_DAC(), converted_val, current_portion, dac_val, tLMS_Ctrl_Header::Data_blocks, tLMS_Ctrl_Packet::Data_field, DEV_TYPE, EXP_BOARD, FW_VER, getFifoData(), glEp0Buffer_Rx, glEp0Buffer_Tx, tLMS_Ctrl_Packet::Header, HW_VER, I2C_init(), I2C_OPENCORES_0_BASE, I2C_read(), I2C_start(), I2C_write(), IORD, IOWR, last_portion, LEDS_BASE, LM75_I2C_ADDR, LMS_CTR_GPIO_BASE, LMS_PROTOCOL_VER, LMS_RST_ACTIVATE, LMS_RST_DEACTIVATE, LMS_RST_PULSE, MAX_MCU_RETRIES, MCU_CONTROL_REG, MCU_FIFO_WR_REG, MCU_retries, MCU_STATUS_REG, tLMS_Ctrl_Header::Periph_ID, PROG_EEPROM, PROG_SRAM, sbi, sc_brdg_data, set_led(), SPI_LMS_BASE, SPI_NR_BRD, SPI_NR_LMS7002M, tLMS_Ctrl_Header::Status, STATUS_BUSY_CMD, STATUS_COMPLETED_CMD, STATUS_ERROR_CMD, STATUS_INVALID_PERIPH_ID_CMD, STATUS_UNKNOWN_CMD, and STATUS_WRONG_ORDER_CMD.
void set_led (unsigned char led_pattern)
Gets led_pattern as parameter in order to write to the register.
Definition at line 100 of file main.c.
References IOWR, and LEDS_BASE.
Referenced by main().
Variable Documentation
uint8_t block
Definition at line 50 of file main.c.
Referenced by altera_avalon_uart_read(), and main().
tBoard_Config_FPGA* Board_Config_FPGA = (tBoard_Config_FPGA*) flash_page_data
Definition at line 65 of file main.c.
uint8_t cmd_errors
Definition at line 50 of file main.c.
Referenced by main().
signed short int converted_val = 300
Definition at line 57 of file main.c.
Referenced by main().
unsigned long int current_portion
Definition at line 61 of file main.c.
Referenced by main().
unsigned char dac_data[2]
Definition at line 55 of file main.c.
unsigned char dac_val = 134
Definition at line 54 of file main.c.
Referenced by main().
unsigned char data_cnt
Definition at line 62 of file main.c.
int flash_data_cnt_free = 0
Definition at line 59 of file main.c.
int flash_data_counter_to_copy = 0
Definition at line 59 of file main.c.
int flash_page = 0
Definition at line 59 of file main.c.
unsigned char flash_page_data[0x100]
Definition at line 64 of file main.c.
int flash_page_data_cnt = 0
Definition at line 59 of file main.c.
unsigned long int fpga_byte
Definition at line 66 of file main.c.
unsigned long int fpga_data
Definition at line 61 of file main.c.
uint8_t glEp0Buffer_Rx[64]
Definition at line 50 of file main.c.
Referenced by main().
uint8_t glEp0Buffer_Tx[64]
Definition at line 50 of file main.c.
Referenced by main().
unsigned long int last_portion
Definition at line 61 of file main.c.
Referenced by main().
tLMS_Ctrl_Packet* LMS_Ctrl_Packet_Rx = (tLMS_Ctrl_Packet*)glEp0Buffer_Rx
Definition at line 52 of file main.c.
tLMS_Ctrl_Packet* LMS_Ctrl_Packet_Tx = (tLMS_Ctrl_Packet*)glEp0Buffer_Tx
Definition at line 51 of file main.c.
uint8_t MCU_retries
Definition at line 48 of file main.c.
Referenced by main().
unsigned char sc_brdg_data[4]
Definition at line 63 of file main.c.
Referenced by main().
uint8_t test
Definition at line 50 of file main.c.