/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/src/alt_find_dev.c File Reference
#include <stddef.h>
*
#include <stdio.h>
*
#include <string.h>
*
#include `sys/alt_dev.h`
*
#include `priv/alt_file.h`
*
#include `alt_types.h`
*
Functions
alt_dev * alt_find_dev (const char *name, alt_llist *llist)
Function Documentation
alt_dev* alt_find_dev (const char * name, alt_llist * llist)
Definition at line 54 of file alt_find_dev.c.
References alt_dev_s::llist, alt_dev_s::name, and alt_llist_s::next.
Referenced by alt_dma_rxchan_open(), alt_dma_txchan_open(), alt_flash_open_dev(), and ALT_OPEN().