/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/drivers/inc/altera_avalon_spi.h File Reference
#include <stddef.h>
*
#include `alt_types.h`
*
Macros
#define ALTERA_AVALON_SPI_INSTANCE(name, device) extern int alt_no_storage
#define ALTERA_AVALON_SPI_INIT(name, device) while (0)
#define ALT_AVALON_SPI_COMMAND_MERGE (0x01)
#define ALT_AVALON_SPI_COMMAND_TOGGLE_SS_N (0x02)
Functions
int alt_avalon_spi_command (alt_u32 base, alt_u32 slave, alt_u32 write_length, const alt_u8 *write_data, alt_u32 read_length, alt_u8 *read_data, alt_u32 flags)
Macro Definition Documentation
#define ALT_AVALON_SPI_COMMAND_MERGE (0x01)
Definition at line 58 of file altera_avalon_spi.h.
Referenced by alt_avalon_spi_command(), and FlashSpiTransfer().
#define ALT_AVALON_SPI_COMMAND_TOGGLE_SS_N (0x02)
Definition at line 64 of file altera_avalon_spi.h.
Referenced by alt_avalon_spi_command().
#define ALTERA_AVALON_SPI_INIT(name, device) while (0)
Definition at line 47 of file altera_avalon_spi.h.
Referenced by alt_sys_init().
#define ALTERA_AVALON_SPI_INSTANCE(name, device) extern int alt_no_storage
Definition at line 46 of file altera_avalon_spi.h.
Function Documentation
int alt_avalon_spi_command (alt_u32 base, alt_u32 slave, alt_u32 write_length, const alt_u8 * write_data, alt_u32 read_length, alt_u8 * read_data, alt_u32 flags)
Definition at line 41 of file altera_avalon_spi.c.
References ALT_AVALON_SPI_COMMAND_MERGE, ALT_AVALON_SPI_COMMAND_TOGGLE_SS_N, ALTERA_AVALON_SPI_CONTROL_SSO_MSK, ALTERA_AVALON_SPI_STATUS_RRDY_MSK, ALTERA_AVALON_SPI_STATUS_TMT_MSK, ALTERA_AVALON_SPI_STATUS_TRDY_MSK, IORD_ALTERA_AVALON_SPI_RXDATA, IORD_ALTERA_AVALON_SPI_STATUS, IOWR_ALTERA_AVALON_SPI_CONTROL, IOWR_ALTERA_AVALON_SPI_SLAVE_SEL, and IOWR_ALTERA_AVALON_SPI_TXDATA.
Referenced by Control_TCXO_ADF(), Control_TCXO_DAC(), CyFxSpiWaitForStatus(), FlashSpiEraseSector(), FlashSpiTransfer(), and main().