/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/inc/sys/alt_sys_wrappers.h File Reference
#include `os/alt_syscall.h`
*
#include <unistd.h>
*
#include <sys/times.h>
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <sys/time.h>
*
Functions
int ALT_CLOSE (int __fd)
int ALT_EXECVE (const char *__path, char *const __argv[], char *const __envp[])
void ALT_EXIT (int __status)
int ALT_FSTAT (int file, struct stat *st)
int ALT_FCNTL (int file, int cmd,...)
pid_t ALT_FORK (void)
pid_t ALT_GETPID (void)
int ALT_GETTIMEOFDAY (struct timeval *ptimeval, struct timezone *ptimezone)
int ALT_IOCTL (int file, int req, void *arg)
int ALT_ISATTY (int file)
int ALT_KILL (int pid, int sig)
int ALT_LINK (const char *existing, const char *new)
off_t ALT_LSEEK (int file, off_t ptr, int dir)
int ALT_OPEN (const char *file, int flags,...)
int ALT_READ (int file, void *ptr, size_t len)
int ALT_RENAME (char *existing, char *new)
void * ALT_SBRK (ptrdiff_t incr)
int ALT_SETTIMEOFDAY (const struct timeval *t, const struct timezone *tz)
int ALT_STAT (const char *file, struct stat *st)
clock_t ALT_TIMES (struct tms *buf)
int ALT_UNLINK (const char *name)
unsigned int ALT_USLEEP (unsigned int us)
int ALT_WAIT (int *status)
int ALT_WRITE (int file, const void *ptr, size_t len)
Variables
char ** ALT_ENVIRON
Function Documentation
int ALT_CLOSE (int __fd)
Definition at line 64 of file alt_close.c.
References ALT_ERRNO, alt_fd_list, alt_release_fd(), alt_dev_s::close, and alt_fd_s::dev.
int ALT_EXECVE (const char * __path, char *const __argv[], char *const __envp[])
void ALT_EXIT (int __status)
Definition at line 52 of file alt_exit.c.
References ALT_LOG_PRINT_BOOT, ALT_OS_STOP, and ALT_SIM_HALT.
int ALT_FCNTL (int file, int cmd, ...)
Definition at line 66 of file alt_fcntl.c.
References ALT_ERRNO, ALT_FCNTL_FLAGS_MASK, ALT_FD_FLAGS_MASK, alt_fd_list, and alt_fd_s::fd_flags.
pid_t ALT_FORK (void)
Definition at line 45 of file alt_fork.c.
References ALT_ERRNO, and ALT_STUB_WARNING.
int ALT_FSTAT (int file, struct stat * st)
Definition at line 89 of file alt_fstat.c.
References ALT_ERRNO, alt_fd_list, alt_fd_s::dev, and alt_dev_s::fstat.
pid_t ALT_GETPID (void)
Definition at line 43 of file alt_getpid.c.
int ALT_GETTIMEOFDAY (struct timeval * ptimeval, struct timezone * ptimezone)
Definition at line 75 of file alt_gettod.c.
References alt_nticks(), alt_resettime, alt_ticks_per_second(), alt_timezone, and ALT_US.
int ALT_IOCTL (int file, int req, void * arg)
Definition at line 106 of file alt_ioctl.c.
References ALT_ERRNO, ALT_FD_DEV, alt_fd_list, alt_fd_lock(), alt_fd_unlock(), alt_fd_s::dev, alt_fd_s::fd_flags, alt_dev_s::ioctl, TIOCEXCL, and TIOCNXCL.
int ALT_ISATTY (int file)
Definition at line 82 of file alt_isatty.c.
References ALT_ERRNO, and alt_fd_list.
int ALT_KILL (int pid, int sig)
Definition at line 49 of file alt_kill.c.
References ALT_ERRNO.
int ALT_LINK (const char * existing, const char * new)
off_t ALT_LSEEK (int file, off_t ptr, int dir)
Definition at line 70 of file alt_lseek.c.
References ALT_ERRNO, alt_fd_list, alt_fd_s::dev, and alt_dev_s::lseek.
int ALT_OPEN (const char * file, int flags, ...)
int ALT_READ (int file, void * ptr, size_t len)
Definition at line 82 of file alt_read.c.
References ALT_ERRNO, alt_fd_list, alt_fd_s::dev, alt_fd_s::fd_flags, and alt_dev_s::read.
int ALT_RENAME (char * existing, char * new)
Definition at line 45 of file alt_rename.c.
References ALT_ERRNO, and ALT_STUB_WARNING.
void* ALT_SBRK (ptrdiff_t incr)
int ALT_SETTIMEOFDAY (const struct timeval * t, const struct timezone * tz)
Definition at line 72 of file alt_settod.c.
References ALT_ERRNO, alt_nticks(), alt_resettime, alt_ticks_per_second(), alt_timezone, and ALT_US.
int ALT_STAT (const char * file, struct stat * st)
Definition at line 49 of file alt_stat.c.
clock_t ALT_TIMES (struct tms * buf)
Definition at line 51 of file alt_times.c.
References ALT_ERRNO, alt_nticks(), and alt_ticks_per_second().
int ALT_UNLINK (const char * name)
unsigned int ALT_USLEEP (unsigned int us)
Definition at line 48 of file alt_usleep.c.
References alt_busy_sleep().
int ALT_WAIT (int * status)
Definition at line 44 of file alt_wait.c.
References ALT_ERRNO.
int ALT_WRITE (int file, const void * ptr, size_t len)
Definition at line 92 of file alt_write.c.
References ALT_ERRNO, alt_fd_list, ALT_LOG_WRITE_FUNCTION, alt_fd_s::dev, alt_fd_s::fd_flags, and alt_dev_s::write.
Variable Documentation
char** ALT_ENVIRON
Definition at line 42 of file alt_environ.c.