/home/erik/git/dev/LimeSDR-USB_GW/ip/ddr2/ddr2_phy_ddr_pins.tcl File Reference
Function Documentation
add_output_clock type pn clockname
Definition at line 898 of file ddr2_phy_ddr_pins.tcl.
References info.
ddr_pin n pin pin_array_name
Definition at line 346 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_ddr_pins().
expr_debug exp
Definition at line 873 of file ddr2_phy_ddr_pins.tcl.
format_3dp x
Definition at line 700 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_flexible_read_capture_timing_analysis(), and perform_flexible_write_launch_timing_analysis().
get_all_dm_pins dqsgroups
Definition at line 458 of file ddr2_phy_ddr_pins.tcl.
get_all_dq_pins dqsgroups
Definition at line 450 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_macro_write_launch_timing_analysis(), verify_high_performance_timing_assumptions(), and verify_high_performance_timing_assumptions_ddr2().
get_all_dqs_pins dqsgroups
Definition at line 442 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_flexible_write_launch_timing_analysis(), perform_macro_read_capture_timing_analysis(), perform_macro_write_launch_timing_analysis(), verify_high_performance_timing_assumptions(), and verify_high_performance_timing_assumptions_ddr2().
get_clock_latency period clockname risefall
Definition at line 817 of file ddr2_phy_ddr_pins.tcl.
References wrap_to_period().
get_clock_phase period clockname risefall
Definition at line 847 of file ddr2_phy_ddr_pins.tcl.
get_colours x y
Definition at line 704 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_flexible_read_capture_timing_analysis(), and perform_flexible_write_launch_timing_analysis().
get_core_full_instance_list corename
Definition at line 949 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_core_instance_list().
get_core_instance_list corename
Definition at line 930 of file ddr2_phy_ddr_pins.tcl.
References get_core_full_instance_list(), and get_timequest_name().
get_ddr_pins instname pins_array_name corename
Definition at line 1538 of file ddr2_phy_ddr_pins.tcl.
References ddr_pin(), map_get_node_name(), post_sdc_message(), and walk_to_pins().
get_deskew_freq_range timing_params period
Definition at line 495 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_tccs(), and get_tsw().
get_fitter_report_pin_info target_pin info_type preferred_report_id ?found_report_id_name?
Definition at line 1298 of file ddr2_phy_ddr_pins.tcl.
References get_fitter_report_pin_info_from_report().
Referenced by get_input_oct_termination(), get_io_interface_type(), get_io_standard(), and get_output_oct_termination().
get_fitter_report_pin_info_from_report target_pin info_type pin_report_id
Definition at line 1268 of file ddr2_phy_ddr_pins.tcl.
References get_report_column().
Referenced by get_fitter_report_pin_info().
get_input_clk_id pll_output_node_id
Definition at line 1074 of file ddr2_phy_ddr_pins.tcl.
References get_input_clk_id(), is_node_type_pll_clk(), and traverse_fanin_up_to_depth().
Referenced by get_input_clk_id().
get_input_oct_termination target_pin
Definition at line 1393 of file ddr2_phy_ddr_pins.tcl.
References get_fitter_report_pin_info().
get_io_interface_type pin_list
Definition at line 1331 of file ddr2_phy_ddr_pins.tcl.
References get_fitter_report_pin_info().
Referenced by get_qdr_tccs_derating(), get_qdr_tsw_derating(), get_tccs(), and get_tsw().
get_io_standard target_pin
Definition at line 1485 of file ddr2_phy_ddr_pins.tcl.
References get_fitter_report_pin_info().
Referenced by get_qdr_tccs_derating(), get_qdr_tsw_derating(), get_tccs(), and get_tsw().
get_operating_conditions_number
Definition at line 1466 of file ddr2_phy_ddr_pins.tcl.
get_output_clock_id ddio_output_pin_list pin_type msg_list_name ?max_search_depth?
Definition at line 1191 of file ddr2_phy_ddr_pins.tcl.
References get_pll_clock().
Referenced by perform_flexible_write_launch_timing_analysis(), and perform_macro_write_launch_timing_analysis().
get_output_clocks type pn
Definition at line 893 of file ddr2_phy_ddr_pins.tcl.
get_output_oct_termination target_pin
Definition at line 1430 of file ddr2_phy_ddr_pins.tcl.
References get_fitter_report_pin_info().
get_pll_clock dest_id_list node_type clock_id_name search_depth
Definition at line 1161 of file ddr2_phy_ddr_pins.tcl.
References traverse_fanin_up_to_depth().
Referenced by get_output_clock_id().
get_qdr_tccs_derating dqs_list
Definition at line 681 of file ddr2_phy_ddr_pins.tcl.
References get_io_interface_type(), and get_io_standard().
get_qdr_tsw_derating dqs_list
Definition at line 665 of file ddr2_phy_ddr_pins.tcl.
References get_io_interface_type(), and get_io_standard().
get_report_column report_id str
Definition at line 1254 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_fitter_report_pin_info_from_report().
get_tccs mem_if_memtype dqs_list period args
Definition at line 532 of file ddr2_phy_ddr_pins.tcl.
References get_deskew_freq_range(), get_io_interface_type(), and get_io_standard().
Referenced by perform_macro_write_launch_timing_analysis().
get_timequest_name hier_name
Definition at line 908 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_core_instance_list().
get_tsw mem_if_memtype dqs_list period args
Definition at line 588 of file ddr2_phy_ddr_pins.tcl.
References get_deskew_freq_range(), get_io_interface_type(), and get_io_standard().
Referenced by perform_macro_read_capture_timing_analysis().
is_node_type_io_clock_divider_clkout node_id
Definition at line 1216 of file ddr2_phy_ddr_pins.tcl.
is_node_type_pin node_id
Definition at line 1058 of file ddr2_phy_ddr_pins.tcl.
is_node_type_pll_clk node_id
Definition at line 1138 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_input_clk_id().
is_node_type_pll_inclk node_id
Definition at line 1033 of file ddr2_phy_ddr_pins.tcl.
list_collection col
Definition at line 467 of file ddr2_phy_ddr_pins.tcl.
map_get_node_name nodes
Definition at line 434 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_ddr_pins().
max a b
Definition at line 731 of file ddr2_phy_ddr_pins.tcl.
max_in_collection col attribute
Definition at line 741 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_flexible_read_capture_non_dqs_timing_analysis(), perform_flexible_read_capture_timing_analysis(), perform_flexible_resync_timing_analysis(), perform_flexible_write_launch_timing_analysis(), and perform_macro_resync_timing_analysis().
min a b
Definition at line 721 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_flexible_read_capture_timing_analysis(), perform_flexible_write_launch_timing_analysis(), and perform_phy_analyses().
min_in_collection col attribute
Definition at line 758 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_flexible_read_capture_non_dqs_timing_analysis(), perform_flexible_read_capture_timing_analysis(), perform_flexible_resync_timing_analysis(), perform_flexible_write_launch_timing_analysis(), and perform_macro_resync_timing_analysis().
min_in_collection_from_name col attribute name
Definition at line 794 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_flexible_read_capture_timing_analysis().
min_in_collection_to_name col attribute name
Definition at line 775 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_flexible_write_launch_timing_analysis().
post_sdc_message msg_type msg
Definition at line 1240 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_ddr_pins().
round_3dp x
Definition at line 696 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_macro_read_capture_timing_analysis(), perform_macro_resync_timing_analysis(), perform_macro_write_launch_timing_analysis(), and perform_macro_write_levelling_timing_analysis().
sett_collection vlist col
Definition at line 476 of file ddr2_phy_ddr_pins.tcl.
Referenced by perform_macro_write_launch_timing_analysis().
sort_proc a b
Definition at line 1601 of file ddr2_phy_ddr_pins.tcl.
traverse_atom_path atom_id atom_oport_id path
Definition at line 3 of file ddr2_phy_ddr_pins.tcl.
References traverse_atom_path().
Referenced by traverse_atom_path(), traverse_to_ddio_out_pll_clock(), traverse_to_dll_id(), and traverse_to_dqs_delaychain_id().
traverse_fanin_up_to_depth node_id match_command edge_type results_array_name depth
Definition at line 1002 of file ddr2_phy_ddr_pins.tcl.
References traverse_fanin_up_to_depth().
Referenced by get_input_clk_id(), get_pll_clock(), and traverse_fanin_up_to_depth().
traverse_to_ddio_out_pll_clock pin msg_list_name family
Definition at line 99 of file ddr2_phy_ddr_pins.tcl.
References traverse_atom_path().
Referenced by verify_high_performance_timing_assumptions(), and verify_high_performance_timing_assumptions_ddr2().
traverse_to_dll dqs_pin msg_list_name
Definition at line 70 of file ddr2_phy_ddr_pins.tcl.
References traverse_to_dll_id().
Referenced by verify_high_performance_timing_assumptions(), and verify_high_performance_timing_assumptions_ddr2().
traverse_to_dll_id dqs_pin msg_list_name
Definition at line 53 of file ddr2_phy_ddr_pins.tcl.
References traverse_atom_path().
Referenced by traverse_to_dll().
traverse_to_dqs_delaychain_id dqs_pin msg_list_name
Definition at line 81 of file ddr2_phy_ddr_pins.tcl.
References traverse_atom_path().
verify_high_performance_timing_assumptions instname pin_array_name write_deskew_t10 discrete_device flexible_timing family
Definition at line 120 of file ddr2_phy_ddr_pins.tcl.
References get_all_dq_pins(), get_all_dqs_pins(), traverse_to_ddio_out_pll_clock(), and traverse_to_dll().
verify_high_performance_timing_assumptions_ddr2 instname pin_array_name write_deskew_t10 flexible_timing family mem_if_memtype
Definition at line 215 of file ddr2_phy_ddr_pins.tcl.
References get_all_dq_pins(), get_all_dqs_pins(), traverse_to_ddio_out_pll_clock(), and traverse_to_dll().
walk_to_all_pins type collection ?depth?
Definition at line 384 of file ddr2_phy_ddr_pins.tcl.
walk_to_pin type mainnode ?depth?
Definition at line 351 of file ddr2_phy_ddr_pins.tcl.
References walk_to_pin().
Referenced by walk_to_pin().
walk_to_pins type collection ?depth?
Definition at line 418 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_ddr_pins().
wrap_to_period period t
Definition at line 813 of file ddr2_phy_ddr_pins.tcl.
Referenced by get_clock_latency().