/home/erik/git/dev/LimeSDR-USB_GW/ip/i2c_opencores_v13/HAL/inc/i2c_opencores.h File Reference
#include `alt_types.h`
*
Macros
#define I2C_OK (0)
#define I2C_ACK (0)
#define I2C_NOACK (1)
#define I2C_ABITRATION_LOST (2)
#define I2C_OPENCORES_INSTANCE(name, dev) extern int alt_no_storage
#define I2C_OPENCORES_INIT(name, dev) while (0)
Functions
void I2C_init (alt_u32 base, alt_u32 clk, alt_u32 speed)
int I2C_start (alt_u32 base, alt_u32 add, alt_u32 read)
alt_u32 I2C_read (alt_u32 base, alt_u32 last)
alt_u32 I2C_write (alt_u32 base, alt_u8 data, alt_u32 last)
Macro Definition Documentation
#define I2C_ABITRATION_LOST (2)
Definition at line 22 of file i2c_opencores.h.
#define I2C_ACK (0)
Definition at line 20 of file i2c_opencores.h.
Referenced by I2C_start(), and I2C_write().
#define I2C_NOACK (1)
Definition at line 21 of file i2c_opencores.h.
Referenced by I2C_start(), and I2C_write().
#define I2C_OK (0)
Definition at line 19 of file i2c_opencores.h.
#define I2C_OPENCORES_INIT(name, dev) while (0)
Definition at line 25 of file i2c_opencores.h.
Referenced by alt_sys_init().
#define I2C_OPENCORES_INSTANCE(name, dev) extern int alt_no_storage
Definition at line 24 of file i2c_opencores.h.
Function Documentation
void I2C_init (alt_u32 base, alt_u32 clk, alt_u32 speed)
Definition at line 28 of file i2c_opencores.c.
Referenced by main().
alt_u32 I2C_read (alt_u32 base, alt_u32 last)
Definition at line 105 of file i2c_opencores.c.
Referenced by main().
int I2C_start (alt_u32 base, alt_u32 add, alt_u32 read)
Definition at line 59 of file i2c_opencores.c.
Referenced by Configure_LM75(), and main().
alt_u32 I2C_write (alt_u32 base, alt_u8 data, alt_u32 last)
Definition at line 145 of file i2c_opencores.c.
Referenced by Configure_LM75(), and main().