/home/erik/git/dev/LimeSDR-USB_GW/ip/ddr2/ddr2_phy_report_timing_core.tcl File Reference
Function Documentation
perform_ac_analyses opcs opcname pin_array_name timing_parameters_array_name summary_name IP_name
Definition at line 1686 of file ddr2_phy_report_timing_core.tcl.
perform_flexible_read_capture_non_dqs_timing_analysis opcs opcname pin_array_name timing_parameters_array_name summary_name MP_name IP_name board_parameters_name
First get the min/max range of DQ and.
clock signals. Can be a result of Now compute the margin from the ideal
Definition at line 908 of file ddr2_phy_report_timing_core.tcl.
References max_in_collection(), and min_in_collection().
perform_flexible_read_capture_timing_analysis opcs opcname pin_array_name timing_parameters_array_name summary_name MP_name IP_name
Read Timing Analysis
Consider some post calibration effects on calibration
Definition at line 564 of file ddr2_phy_report_timing_core.tcl.
References format_3dp(), get_colours(), max_in_collection(), min(), min_in_collection(), and min_in_collection_from_name().
perform_flexible_resync_timing_analysis opcs opcname pin_array_name timing_parameters_array_name summary_name MP_name IP_name SSN_name board_parameters_name
Definition at line 1209 of file ddr2_phy_report_timing_core.tcl.
References max_in_collection(), and min_in_collection().
perform_flexible_write_launch_timing_analysis opcs opcname pin_array_name timing_parameters_array_name summary_name MP_name IP_name
Write Timing Analysis
Consider some post calibration effects on calibration
Definition at line 5 of file ddr2_phy_report_timing_core.tcl.
References format_3dp(), get_all_dqs_pins(), get_colours(), get_output_clock_id(), max_in_collection(), min(), min_in_collection(), and min_in_collection_to_name().
perform_flexible_write_levelling_timing_analysis opcs opcname pin_array_name timing_parameters_array_name summary_name MP_name IP_name SSN_name board_parameters_name ISI_parameters_name
Definition at line 1433 of file ddr2_phy_report_timing_core.tcl.
perform_macro_read_capture_timing_analysis opcs opcname pin_array_name timing_parameters_array_name summary_name IP_name
Definition at line 1020 of file ddr2_phy_report_timing_core.tcl.
References get_all_dqs_pins(), get_tsw(), and round_3dp().
perform_macro_resync_timing_analysis opcs opcname pin_array_name timing_parameters_array_name summary_name MP_name IP_name board_parameters_name
Calibrated Path Analysis
Definition at line 1100 of file ddr2_phy_report_timing_core.tcl.
References max_in_collection(), min_in_collection(), and round_3dp().
perform_macro_write_launch_timing_analysis opcs opcname pin_array_name timing_parameters_array_name summary_name IP_name ISI_name
Definition at line 478 of file ddr2_phy_report_timing_core.tcl.
References get_all_dq_pins(), get_all_dqs_pins(), get_output_clock_id(), get_tccs(), round_3dp(), and sett_collection().
perform_macro_write_levelling_timing_analysis opcs opcname pin_array_name timing_parameters_array_name summary_name MP_name IP_name board_parameters_name ISI_parameters_name
Definition at line 1364 of file ddr2_phy_report_timing_core.tcl.
References round_3dp().
perform_phy_analyses opcs opcname pin_array_name timing_parameters_array_name summary_name IP_name
Other Timing Analysis
Definition at line 1616 of file ddr2_phy_report_timing_core.tcl.
References min().