/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/drivers/src/i2c_opencores.c File Reference
#include `alt_types.h`
*
#include `i2c_opencores_regs.h`
*
#include `i2c_opencores.h`
*
Functions
void I2C_init (alt_u32 base, alt_u32 clk, alt_u32 speed)
int I2C_start (alt_u32 base, alt_u32 add, alt_u32 read)
alt_u32 I2C_read (alt_u32 base, alt_u32 last)
alt_u32 I2C_write (alt_u32 base, alt_u8 data, alt_u32 last)
Function Documentation
void I2C_init (alt_u32 base, alt_u32 clk, alt_u32 speed)
Definition at line 28 of file i2c_opencores.c.
References I2C_OPENCORES_CR_IACK_MSK, I2C_OPENCORES_CTR_EN_MSK, IOWR_I2C_OPENCORES_CR, IOWR_I2C_OPENCORES_CTR, IOWR_I2C_OPENCORES_PRERHI, and IOWR_I2C_OPENCORES_PRERLO.
Referenced by main().
alt_u32 I2C_read (alt_u32 base, alt_u32 last)
Definition at line 105 of file i2c_opencores.c.
References I2C_OPENCORES_CR_NACK_MSK, I2C_OPENCORES_CR_RD_MSK, I2C_OPENCORES_CR_STO_MSK, I2C_OPENCORES_SR_TIP_MSK, IORD_I2C_OPENCORES_RXR, IORD_I2C_OPENCORES_SR, and IOWR_I2C_OPENCORES_CR.
Referenced by main().
int I2C_start (alt_u32 base, alt_u32 add, alt_u32 read)
Definition at line 59 of file i2c_opencores.c.
References I2C_ACK, I2C_NOACK, I2C_OPENCORES_CR_STA_MSK, I2C_OPENCORES_CR_WR_MSK, I2C_OPENCORES_SR_RXNACK_MSK, I2C_OPENCORES_SR_TIP_MSK, IORD_I2C_OPENCORES_SR, IOWR_I2C_OPENCORES_CR, and IOWR_I2C_OPENCORES_TXR.
Referenced by Configure_LM75(), and main().
alt_u32 I2C_write (alt_u32 base, alt_u8 data, alt_u32 last)
Definition at line 145 of file i2c_opencores.c.
References I2C_ACK, I2C_NOACK, I2C_OPENCORES_CR_STO_MSK, I2C_OPENCORES_CR_WR_MSK, I2C_OPENCORES_SR_RXNACK_MSK, I2C_OPENCORES_SR_TIP_MSK, IORD_I2C_OPENCORES_SR, IOWR_I2C_OPENCORES_CR, and IOWR_I2C_OPENCORES_TXR.
Referenced by Configure_LM75(), and main().