/home/erik/git/dev/LimeSDR-USB_GW/software/lms_ctr_bsp/HAL/inc/sys/alt_cache.h File Reference
#include <stdlib.h>
*
#include `alt_types.h`
*
Functions
void alt_icache_flush (void *start, alt_u32 len)
void alt_dcache_flush (void *start, alt_u32 len)
void alt_dcache_flush_no_writeback (void *start, alt_u32 len)
void alt_icache_flush_all (void)
void alt_dcache_flush_all (void)
volatile void * alt_uncached_malloc (size_t size)
void alt_uncached_free (volatile void *ptr)
volatile void * alt_remap_uncached (void *ptr, alt_u32 len)
void * alt_remap_cached (volatile void *ptr, alt_u32 len)
Function Documentation
void alt_dcache_flush (void * start, alt_u32 len)
Definition at line 46 of file alt_dcache_flush.c.
References ALT_FLUSH_DATA, and NIOS2_DCACHE_LINE_SIZE.
Referenced by alt_ecc_fatal_exception_register(), and alt_uncached_malloc().
void alt_dcache_flush_all (void)
Definition at line 41 of file alt_dcache_flush_all.c.
References __asm__(), NIOS2_DCACHE_LINE_SIZE, and NIOS2_DCACHE_SIZE.
Referenced by alt_load().
void alt_dcache_flush_no_writeback (void * start, alt_u32 len)
Definition at line 49 of file alt_dcache_flush_no_writeback.c.
References ALT_FLUSH_DATA_NO_WRITEBACK, and NIOS2_DCACHE_LINE_SIZE.
void alt_icache_flush (void * start, alt_u32 len)
Definition at line 42 of file alt_icache_flush.c.
References __asm__(), NIOS2_ICACHE_LINE_SIZE, and NIOS2_ICACHE_SIZE.
Referenced by alt_icache_flush_all().
void alt_icache_flush_all (void)
Definition at line 41 of file alt_icache_flush_all.c.
References alt_icache_flush(), and NIOS2_ICACHE_SIZE.
Referenced by alt_load().
void* alt_remap_cached (volatile void * ptr, alt_u32 len)
Definition at line 41 of file alt_remap_cached.c.
References ALT_LINK_ERROR.
volatile void* alt_remap_uncached (void * ptr, alt_u32 len)
Definition at line 49 of file alt_remap_uncached.c.
References ALT_LINK_ERROR.
void alt_uncached_free (volatile void * ptr)
Definition at line 40 of file alt_uncached_free.c.
References ALT_LINK_ERROR.
volatile void* alt_uncached_malloc (size_t size)
Definition at line 42 of file alt_uncached_malloc.c.
References ALT_CPU_DCACHE_LINE_SIZE, alt_dcache_flush(), and ALT_LINK_ERROR.